use anyhow::Result;

pub async fn run(shell: &str) -> Result<()> {
    let wake_bin = std::env::current_exe()
        .map(|p| p.to_string_lossy().to_string())
        .unwrap_or_else(|_| "wake".to_string());

    let hooks = match shell {
        "zsh" => format!(
            r#"# Wake shell hooks for zsh
# Generated by: wake init zsh

if [[ -n "$WAKE_SESSION" ]]; then
    __wake_preexec() {{
        "{wake_bin}" __hook cmd-start --cmd "$1"
    }}
    __wake_precmd() {{
        "{wake_bin}" __hook cmd-end --exit-code $? --duration $SECONDS
    }}
    autoload -Uz add-zsh-hook
    add-zsh-hook preexec __wake_preexec
    add-zsh-hook precmd __wake_precmd
fi
"#
        ),
        "bash" => format!(
            r#"# Wake shell hooks for bash
# Generated by: wake init bash

if [[ -n "$WAKE_SESSION" ]]; then
    __wake_preexec() {{
        "{wake_bin}" __hook cmd-start --cmd "$BASH_COMMAND"
    }}
    trap '__wake_preexec' DEBUG

    PROMPT_COMMAND='{wake_bin} __hook cmd-end --exit-code $? --duration $SECONDS; '"$PROMPT_COMMAND"
fi
"#
        ),
        other => anyhow::bail!("Unsupported shell: {other}. Supported: zsh, bash"),
    };

    print!("{hooks}");
    Ok(())
}
